version: '3.2'

services:
  python:
    build: .
    depends_on: 
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - 6379:6379
  nginx:
    image: nginx:latest
    ports:
        - "8080:8080"
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
        - python
